import Product from "./Product";

export const products = [
  {
    id: 1,
    name: "Laptop",
    description: "14 inch, 16GB RAM, 512GB SSD",
    price: 1200.0,
    category: "Electronics",
    stock: 25,
  },
  {
    id: 2,
    name: "Smartphone",
    description: "6.5 inch, 128GB Storage",
    price: 800.0,
    category: "Electronics",
    stock: 50,
  },
  {
    id: 3,
    name: "Headphones",
    description: "Noise-cancelling, Wireless",
    price: 150.0,
    category: "Accessories",
    stock: 100,
  },
  {
    id: 4,
    name: "Smartwatch",
    description: "Heart rate monitor, GPS",
    price: 200.0,
    category: "Electronics",
    stock: 40,
  },
  {
    id: 5,
    name: "Tablet",
    description: "10 inch, 64GB Storage",
    price: 300.0,
    category: "Electronics",
    stock: 30,
  },
  {
    id: 6,
    name: "Camera",
    description: "20MP, 4K Video",
    price: 500.0,
    category: "Electronics",
    stock: 15,
  },
  {
    id: 7,
    name: "Printer",
    description: "Laser, Wireless",
    price: 120.0,
    category: "Office Supplies",
    stock: 20,
  },
  {
    id: 8,
    name: "Monitor",
    description: "27 inch, 4K",
    price: 350.0,
    category: "Electronics",
    stock: 10,
  },
  {
    id: 9,
    name: "Keyboard",
    description: "Mechanical, RGB",
    price: 80.0,
    category: "Accessories",
    stock: 60,
  },
  {
    id: 10,
    name: "Mouse",
    description: "Wireless, Ergonomic",
    price: 40.0,
    category: "Accessories",
    stock: 70,
  },
  {
    id: 11,
    name: "External Hard Drive",
    description: "1TB, USB 3.0",
    price: 100.0,
    category: "Storage",
    stock: 35,
  },
  {
    id: 12,
    name: "Router",
    description: "WiFi 6, Dual-band",
    price: 90.0,
    category: "Networking",
    stock: 25,
  },
  {
    id: 13,
    name: "Speakers",
    description: "Bluetooth, Portable",
    price: 60.0,
    category: "Audio",
    stock: 50,
  },
  {
    id: 14,
    name: "Webcam",
    description: "1080p, Autofocus",
    price: 70.0,
    category: "Accessories",
    stock: 40,
  },
  {
    id: 15,
    name: "Projector",
    description: "1080p, HDMI",
    price: 250.0,
    category: "Electronics",
    stock: 10,
  },
  {
    id: 16,
    name: "Fitness Tracker",
    description: "Step counter, Sleep monitor",
    price: 50.0,
    category: "Wearables",
    stock: 45,
  },
  {
    id: 17,
    name: "Gaming Console",
    description: "4K HDR, 1TB Storage",
    price: 400.0,
    category: "Gaming",
    stock: 15,
  },
  {
    id: 18,
    name: "VR Headset",
    description: "Standalone, 64GB",
    price: 300.0,
    category: "Gaming",
    stock: 20,
  },
  {
    id: 19,
    name: "E-reader",
    description: "6 inch, 8GB Storage",
    price: 120.0,
    category: "Electronics",
    stock: 30,
  },
  {
    id: 20,
    name: "Drone",
    description: "4K Camera, GPS",
    price: 600.0,
    category: "Electronics",
    stock: 12,
  },
];

{
  console.log(products);
}
